name: Build

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
    run-linters:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 19

            - uses: pnpm/action-setup@v2
              with:
                  version: latest

            - name: Add Rasbian package repositories
              run: echo deb http://archive.raspberrypi.org/debian/ bullseye main | sudo tee /etc/apt/sources.list.d/raspberrypi.list && sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7FA3303E

            - name: Install PiGPIO
              run: sudo apt-get update && sudo apt-get install -y pigpio

            - name: Install Node.js dependencies
              run: pnpm install

            - name: Set sample configs for building
              run: cp config/config.example.json config/config.json && cp config/credentials.example.json config/credentials.json

            - name: Build using TSC
              run: pnpm run build

            - name: Remove sample configs for building
              run: rm config/config.json && rm config/credentials.json

            - name: Copy important files to the build
              run: cp package.json dist/package.json && cp -R scripts dist/scripts/ && cp pnpm-lock.yaml dist/pnpm-lock.yaml && cp ecosystem.config.cjs dist/ecosystem.config.js

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist/
                  if-no-files-found: error
